version: '3'

services:
    postgres:
      image: debezium/example-postgres:1.9
      container_name: postgres
      ports:
      - 5433:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - PGDATA=/var/lib/postgresql/data/pgdata
        - POSTGRES_HOST_AUTH_METHOD="trust"
      networks:
        - mynetwork

    zookeeper:
      image: wurstmeister/zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 2181:2181
      networks:
        - mynetwork
          
    kafka:
      image: wurstmeister/kafka:latest
      restart: "no"
      links:
        - zookeeper
      ports:
        - 9092:9092
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
        KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      networks:
        - mynetwork
    
    jobmanager:
      build: .
      image: flink:java17
      container_name: jobmanager
      restart: always
      expose:
        - "6123"
      ports:
        - "8085:8081"
      command: jobmanager
      environment:
        - JOB_MANAGER_RPC_ADDRESS=jobmanager
      networks:
        - mynetwork
        
    taskmanager:
      build: .
      image: flink:java17
      container_name: taskmanager
      restart: always
      expose:
        - "6121"
        - "6122"
      depends_on:
        - jobmanager
      command: taskmanager
      scale: 1
      links:
        - "jobmanager:jobmanager"
      environment:
        - JOB_MANAGER_RPC_ADDRESS=jobmanager
        - taskmanager.numberOfTaskSlots=10
      networks:
        - mynetwork

    debezium:
      image: debezium/connect:1.9
      ports:
        - 8083:8083
      environment:
        CONFIG_STORAGE_TOPIC: my_connect_configs
        OFFSET_STORAGE_TOPIC: my_connect_offsets
        STATUS_STORAGE_TOPIC: my_connect_statuses
        BOOTSTRAP_SERVERS: kafka:29092
      depends_on:
        - kafka
        - zookeeper
        - postgres  
      networks:
        - mynetwork

    kafdrop:
      image: obsidiandynamics/kafdrop
      restart: "no"
      environment:
        KAFKA_BROKERCONNECT: "kafka:29092"
      ports:
        - 9000:9000
      depends_on:
        - kafka
      networks:
        - mynetwork    

    debezium-ui:
      image: debezium/debezium-ui:2.4
      depends_on:
        - debezium
      container_name: debezium_ui
      restart: always
      ports:
        - "8081:8080"
      environment:
        - KAFKA_CONNECT_URIS=http://debezium:8083
      networks:
        - mynetwork
            
networks:
  mynetwork:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mynetwork
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.enable_icc: "true"